{BACK}

<h3>{SETTINGS_LABEL}</h3>

<!-- BEGIN MESSAGE -->
<h4>{MESSAGE}</h4>
<!-- END MESSAGE -->

{START_FORM}
{SHOW_ON_HOME} {SHOW_ON_HOME_LABEL} {SHOW_ON_HOME_HELP}<br />
{ALLOW_ANON_VIEW} {ALLOW_ANON_VIEW_LABEL} {ALLOW_ANON_VIEW_HELP}<br />
{ALLOW_PAGE_EDIT} {ALLOW_PAGE_EDIT_LABEL} {ALLOW_PAGE_EDIT_HELP}<br />
{ALLOW_IMAGE_UPLOAD} {ALLOW_IMAGE_UPLOAD_LABEL} {ALLOW_IMAGE_UPLOAD_HELP}<br />
{ALLOW_BBCODE} {ALLOW_BBCODE_LABEL} {ALLOW_BBCODE_HELP}<br />
{EXT_CHARS_SUPPORT} {EXT_CHARS_SUPPORT_LABEL} {EXT_CHARS_SUPPORT_HELP}<br />
{ADD_TO_TITLE} {ADD_TO_TITLE_LABEL} {ADD_TO_TITLE_HELP}<br />
{FORMAT_TITLE} {FORMAT_TITLE_LABEL} {FORMAT_TITLE_HELP}<br />
{SHOW_MODIFIED_INFO} {SHOW_MODIFIED_INFO_LABEL} {SHOW_MODIFIED_INFO_HELP}<br />
{MONITOR_EDITS} {MONITOR_EDITS_LABEL} {MONITOR_EDITS_HELP}<br /><br />

{ADMIN_EMAIL_LABEL}: {ADMIN_EMAIL} {ADMIN_EMAIL_HELP}<br /><br />

{EMAIL_TEXT_LABEL}: {EMAIL_TEXT_HELP}<br />
{EMAIL_TEXT}<br /><br />

{DEFAULT_PAGE_LABEL}: {DEFAULT_PAGE} {DEFAULT_PAGE_HELP}<br /><br />

{EXT_PAGE_TARGET_LABEL}: {EXT_PAGE_TARGET} {EXT_PAGE_TARGET_HELP}<br /><br />

<em>{MENU_ITEMS_LABEL}</em> {MENU_ITEMS_HELP}<br />
{IMMUTABLE_PAGE} {IMMUTABLE_PAGE_LABEL}<br />
{RAW_TEXT} {RAW_TEXT_LABEL}<br />
{PRINT_VIEW} {PRINT_VIEW_LABEL}<br /><br />

<em>{DISCUSSION_SECTION_LABEL}
<!-- BEGIN COMMENTS_NOTE -->
 ({COMMENTS_LABEL})
<!-- END COMMENTS_NOTE -->
</em> {DISCUSSION_HELP}<br />
{DISCUSSION} {DISCUSSION_LABEL}<br />
{DISCUSSION_ANON} {DISCUSSION_ANON_LABEL}<br /><br />

{SAVE}
{END_FORM}

<hr />

{PAGE_LIST}